### ISSUE TITLE
Spinner shown only once

### ISSUE THREAD

**Issue by Coffei** [thomasboyt/react-spin#1]
When stopped prop changes from true to false, the  spinner is not shown.

**Comment by Coffei** [comment]
The cause seems to be calling spin on line 21 without the target DOM node. I have created a pull request #2 for this. Please review and merge.

**Comment by samsel** [comment]
@thomasboyt can this change be published to npm? thanks!

**Comment by thomasboyt** [comment]
Sorry, just now seeing this - will try to get it merged tonight :)

**Comment by Coffei** [comment]
Hi, any update on this? It is really just a very small fix and it should not take more than a few minutes to merge and test it.

**Comment by thomasboyt** [comment]
merged https://github.com/thomasboyt/react-spin/pull/2, thanks and sorry for such a long delay!
