### ISSUE TITLE
Error when building with browserify

### ISSUE THREAD

**Issue by chadly** [thomasboyt/react-spin#4]
I'm trying to use your component and getting an error when using browserify:

> Error: Parsing file `node_modules\react-spin\src\main.js`: Unexpected token (29:6)

Specifically, I am [running into this problem](https://github.com/andreypopp/reactify#code-in-3rd-party-packages-isnt-being-transformed-by-reactify).

It can be fixed by running the `jsx` transform before publishing to npm OR adding the following to your `package.json`:

``` js
"browserify": {
  "transform": ["reactify"]
}
```

I think this is the same issue that #3 is trying to address.

**Comment by captDaylight** [comment]
+1 getting the same error

**Comment by rdjpalmer** [comment]
+1, same error with webpack

**Comment by thomasboyt** [comment]
Should be fixed in `0.4.0` just published to NPM, sorry for the delay

**Comment by 9mm** [comment]
I'm getting the same problem except with webpack, not quite sure to go about fixing that.

**Comment by 9mm** [comment]
My bad I didnt see 0.4.0 was the latest (github is at 0.3.0)
